### ISSUE TITLE
[BUG]: Navbar(drop down menu) in team section not working for mobile devices 

### ISSUE THREAD

**Issue by Adityalad-25** [SyedImtiyaz-1/PreciousServices#130]
**Describe the bug**
The mobile device navigation menu (dropdown) is not functioning correctly in the team section. I have provided a video URL demonstrating this issue: [Video link](https://drive.google.com/file/d/17U0sCGTll2H3vroVP9kPdMUoDKi508Kq/view?usp=sharing).

**To Reproduce**
1. Navigate to the specified location.
2. Click on a particular element or perform certain actions.
3. Scroll down to a specific section.
4. Observe the issue as shown in the video.

**Expected behavior**
The dropdown menu button should be correctly positioned on the right side and should function properly when clicked on mobile devices.

**Screenshots/ Video**

<img width="200" alt="Screenshot 2023-10-02 at 5 45 04 AM" src="https://github.com/SyedImtiyaz-1/PreciousServices-/assets/97255480/ce2b94d1-ebc7-459d-92f6-92ff3239be30">

[Video link](https://drive.google.com/file/d/17U0sCGTll2H3vroVP9kPdMUoDKi508Kq/view?usp=sharing) : https://drive.google.com/file/d/17U0sCGTll2H3vroVP9kPdMUoDKi508Kq/view?usp=sharing

**Additional context**
Please ensure you have completed the following tasks before submitting your contribution:

- [x] I have checked the existing issues.
- [x] [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Have you added your name in [CONTRIBUTING.md](https://github.com/SyedImtiyaz-1/PreciousServices/blob/main/CONTRIBUTING.md)?
- [x] I want to work on this issue.

 Please tag this issue with hacktoberfest tag .
 
Feel free to connect with me on [LinkedIn](https://www.linkedin.com/in/adityalad2003/). Let's collaborate to resolve this issue.

**Comment by SyedImtiyaz-1** [comment]
Great, please fix that.

**Comment by Adityalad-25** [comment]
ok

**Comment by Adityalad-25** [comment]
issue 130 fixed

**Comment by Adityalad-25** [comment]
please review my pull request (PR #145) and if it's okay then merge it also assign me any chnages if needed .
