### ISSUE TITLE
[ui-upgrade]: Contact form font-size for accessibility

### ISSUE THREAD

**Issue by fjuren** [SyedImtiyaz-1/PreciousServices#131]
**Describe the bug**
The font-size on the contact form is quite small and may not be legible by users with poor eyesight.

**To Reproduce**
1. Client 'Contact' on the top nav
2. Type in values on the contact form
3. View small font-size

**Expected behavior**
Font size should be closer to 16px

**Additional context**
This is an accessiblity improvement to the website.

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Have you added your name in [CONTRIBUTING.md](https://github.com/SyedImtiyaz-1/PreciousServices/blob/main/CONTRIBUTING.md)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://www.linkedin.com/in/fabianjuren/)
Let's Connect 1:1 - [Click Here](https://github.com/fjuren)

**Comment by fjuren** [comment]
Please tag with hacktoberfest2023. Thanks

**Comment by sameer1612** [comment]
I can fix this, pretty small change.  Do assign when you're available  @SyedImtiyaz-1.  Thanks!

**Comment by sysreset999** [comment]
please assign me this issue
