### ISSUE TITLE
Fix: inconsistent login buttons

### ISSUE THREAD

**Issue by Petsamuel** [SyedImtiyaz-1/PreciousServices#16]
buttons are not consistent. 

![image](https://github.com/SyedImtiyaz-1/hacktoberfest/assets/65086865/9c1d6a88-d7ad-4453-9910-dd73664f6685)

**Comment by SyedImtiyaz-1** [comment]
Go for it. @Petsamuel

**Comment by AdityaP7649** [comment]
Hi there! I'm interested in working on this issue. It aligns with my skills. Could you please assign this issue to me. Thanks!

**Comment by Petsamuel** [comment]
> Go for it. @Petsamuel 

Thanks

**Comment by Nikhil743** [comment]
I want to work on this issue for hacktoberfest. Please assgin it to me

**Comment by Petsamuel** [comment]
> I want to work on this issue for hacktoberfest. Please assgin it to me

IM WORKING ON THIS.... LOOK FOR OTHER ISSUES
