### ISSUE TITLE
[BUG]: Project Cards are not responsive and get overlapped with footer

### ISSUE THREAD

**Issue by ratishjain12** [SyedImtiyaz-1/PreciousServices#165]
**Describe the bug**
@SyedImtiyaz-1 I want to improve cards and fix the overlapping of this section kindly assign it to me :)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [ ] I have checked the existing issues
- [ ]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [ ] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [ ] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SyedImtiyaz-1** [comment]
Okay assigning to you fix this thing 
[Screencast from 02-10-23 06:45:53 PM IST.webm](https://github.com/SyedImtiyaz-1/PreciousServices/assets/121503426/eef8fe88-9162-416d-a3ea-32a8a5eac01b)

**Comment by ratishjain12** [comment]
> Okay assigning to you fix this thing [Screencast from 02-10-23 06:45:53 PM IST.webm](https://github.com/SyedImtiyaz-1/PreciousServices/assets/121503426/eef8fe88-9162-416d-a3ea-32a8a5eac01b)

On it!!
