### ISSUE TITLE
[BUG]: Project Popup img rendering issue

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [SyedImtiyaz-1/PreciousServices#169]
### Can anyone fix this ? 

1. Go to projects
2. Click on eye icon to review the project

Issue Screenshot - As you can see img size is too small and it is looking weird. (PC/Laptop Images)
![Screenshot from 2023-10-02 19-01-30](https://github.com/SyedImtiyaz-1/-PreciousServices/assets/121503426/4a5efe84-dfe8-4bb8-ac14-ed03ccd82205)

Mobile View are Good -
![image](https://github.com/SyedImtiyaz-1/-PreciousServices/assets/121503426/0f9330e1-96f9-4b63-888f-7a3a5c7096d8)

**Comment by growupanand** [comment]
@SyedImtiyaz-1 
Can you please review the [PR](https://github.com/SyedImtiyaz-1/PreciousServices/pull/181)
