### ISSUE TITLE
[BUG]: Logo For Mobile Ratio

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [SyedImtiyaz-1/PreciousServices#170]
[Screencast from 02-10-23 07:13:01 PM IST.webm](https://github.com/SyedImtiyaz-1/PreciousServices/assets/121503426/3810dbd9-466e-445b-9103-c72216a5f243)

Logo is not properly aligned and it looking too small.

**Comment by Rehan52004** [comment]
please assign me this issue

**Comment by SyedImtiyaz-1** [comment]
> please assign me this issue

Someone is already working on this please search for more issues.
