### ISSUE TITLE
[BUG]: Logo in the navbar is stretched in mobile view

### ISSUE THREAD

**Issue by ketan-sonar** [SyedImtiyaz-1/PreciousServices#171]
**Describe the bug**
The logo in the navbar appears stretched in the mobile view.

**To Reproduce**
1. Go to the home page.
2. Go into mobile view.
3. Look at the logo in the navbar.

**Expected behavior**
It should have a proper width so that it does not appear stretched.

**Screenshots**
<img width="607" alt="Screenshot 2023-10-02 at 19 12 11" src="https://github.com/SyedImtiyaz-1/PreciousServices/assets/62693272/f4134b9d-5eb4-4ef5-9348-2245a4b8a192">
Look at the screenshot attached.

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/ketansonar)

**Comment by Rehan52004** [comment]
Please, assign to me

**Comment by ketan-sonar** [comment]
@SyedImtiyaz-1 I'm already working on it.

**Comment by Rehan52004** [comment]
ok

**Comment by sahashorha** [comment]
I want work on this please assign me

**Comment by ketan-sonar** [comment]
I have already fixed it.
