### ISSUE TITLE
chore: project addition of microsoft clone

### ISSUE THREAD

**Issue by hsayvaidya23** [SyedImtiyaz-1/PreciousServices#188]
**Describe the bug**
Add a Microsoft clone project

**Expected behavior**
A project name "MICROSOFT CLONE " is added to the projects section.

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x] [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SyedImtiyaz-1** [comment]
@hsayvaidya23 This project have DB ?
