### ISSUE TITLE
Remove Modules

### ISSUE THREAD

**Issue by Intekhabilyas** [SyedImtiyaz-1/PreciousServices#20]
@SyedImtiyaz-1 I want to Remove Node Modules

**Comment by SyedImtiyaz-1** [comment]
Go for it. @Intekhabilyas

**Comment by 07tAnYa** [comment]
hey, I am working on this.

**Comment by SyedImtiyaz-1** [comment]
@07tAnYa It's currently assigned to @Intekhabilyas 
Please check other issues.
