### ISSUE TITLE
[BUG]: Improving the styling of login button in mobile view It is Not visible

### ISSUE THREAD

**Issue by rutikgagare** [SyedImtiyaz-1/PreciousServices#214]
**Describe the bug**
In mobile view login button is not visible and navbar is not looking great so i can style it and make is attractive.

**To Reproduce**

**Expected behavior**
Without hovering of a button login should be visible It should have proper color.

**Screenshots**
![issue_screenshot](https://github.com/SyedImtiyaz-1/PreciousServices/assets/85502114/42de88c1-5ad9-4056-a393-b9ab6df61210)

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [ ✔] I have checked the existing issues
- [ ✔]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [ ✔] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [ ✔] I want to work on this issue

please assign me this issue @SyedImtiyaz-1

**Comment by khareutkarshk** [comment]
I want to work in this issue, please assign so that I may proceed @SyedImtiyaz-1
