### ISSUE TITLE
Project Addition: Resume

### ISSUE THREAD

**Issue by hollermay** [SyedImtiyaz-1/PreciousServices#227]
I would like to add a resume project template for this repository, you can check my resume I designed here at - https://hollermay.github.io/Resume

**Comment by SyedImtiyaz-1** [comment]
@hollermay Please add project which have Backend and proper functionality

**Comment by hollermay** [comment]
@SyedImtiyaz-1 , I've added my contributor.md update, please merge

**Comment by hollermay** [comment]
> @hollermay Please add project which have Backend and proper functionality

Okay
