### ISSUE TITLE
[BUG]: Text Auto Capitalization Bug

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [SyedImtiyaz-1/PreciousServices#230]
Hello Contributors,
Please check the issue here :

Close the Capitilization Gmail is converting to Capital G evertime and fix every letter in the website as per the Capitalization. 

![image](https://github.com/SyedImtiyaz-1/PreciousServices/assets/121503426/1896ba34-1fd9-49fb-8a4d-f18c952af7fa)

**Comment by sukhmani1303** [comment]
@SyedImtiyaz-1 kindly assign me this issue!

**Comment by sukhmani1303** [comment]
also, the "contact number" field takes characters which should not happen... can you make it a different issue under "hacktoberfest" & assign me that issue as well?

**Comment by SyedImtiyaz-1** [comment]
Sure.

**Comment by sukhmani1303** [comment]
@SyedImtiyaz-1 can you assign me for the contact number issue as well?

**Comment by SyedImtiyaz-1** [comment]
@sukhmani1303  Create issue first
