### ISSUE TITLE
[BUG]: Login button is not opening Google AuthO login 

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [SyedImtiyaz-1/PreciousServices#231]
Hello Contributors,

## - Fix the mention issue here under `HacktoberFest-23`

**Comment by Sha1kh4** [comment]
Please assign so i can start working on this issue.

**Comment by ketan-sonar** [comment]
I have fixed this issue and raised a pr #235.
Please review it and tell me if any changes are needed.
