### ISSUE TITLE
[BUG]: Contact Number takes character input

### ISSUE THREAD

**Issue by sukhmani1303** [SyedImtiyaz-1/PreciousServices#236]
**Describe the bug**
The contact number field takes characters as input but should only be restricted to numbers 

<img width="236" alt="image" src="https://github.com/SyedImtiyaz-1/PreciousServices/assets/101919460/a7ed3650-9550-4178-88b5-19a4f292caf1">

**Comment by Pratikdate** [comment]
Assign me i will work on it

**Comment by Ankit-Matth** [comment]
Hello Sir, I have fixed this bug, please assigned it to me.
