### ISSUE TITLE
[BUG]: Repository does not follow values of event (HacktoberFest)

### ISSUE THREAD

**Issue by Rohit-Yadavv** [SyedImtiyaz-1/PreciousServices#245]
**Describe the bug**
Pull Request are Excluded from HacktoberFest showing repository not following values of event

![image](https://github.com/SyedImtiyaz-1/PreciousServices/assets/126584837/38482b67-4e8d-46d5-badc-2b6d641caeaf)

![image](https://github.com/SyedImtiyaz-1/PreciousServices/assets/126584837/756433ff-0173-4e0b-b82c-ee055c48878b)

![image](https://github.com/SyedImtiyaz-1/PreciousServices/assets/126584837/b63e5409-6bf8-4dd2-88c9-3dfa1c49c764)

**Comment by SyedImtiyaz-1** [comment]
This issue is fixed now new contribution will going to count from now.

**Comment by Rohit-Yadavv** [comment]
What about Old...?
