### ISSUE TITLE
REPOSITORY EXCLUDED FROM HACKTOBERFEST!

### ISSUE THREAD

**Issue by sukhmani1303** [SyedImtiyaz-1/PreciousServices#249]
@SyedImtiyaz-1 kindly contact the ```Hacktoberfest``` Team & resolve this issue asap. Your repository has been excluded from Hacktoberfest & all the PRs are now marked as ```EXCLUDED``` & wont be counted!

<img width="934" alt="image" src="https://github.com/SyedImtiyaz-1/PreciousServices/assets/101919460/9285bb2c-8546-4a41-860e-b0594a657e61">

**Comment by SyedImtiyaz-1** [comment]
New Repo : https://github.com/SyedImtiyaz-1/Code-Shop
