### ISSUE TITLE
Feature: Create scroll to top button.

### ISSUE THREAD

**Issue by ronisarkarexe** [SyedImtiyaz-1/PreciousServices#25]
![scroll1](https://github.com/SyedImtiyaz-1/PreciousServices/assets/76697055/62e99b1c-2e15-44b9-9004-fd2d80badcb1)

new feature:
1. when the user comes button section, the user can move the button to the top with one click.

**Comment by SyedImtiyaz-1** [comment]
Great Idea @ronisarkarexe
