### ISSUE TITLE
[BUG]: UI/UX Design Issue

### ISSUE THREAD

**Issue by barkhaaroraa** [SyedImtiyaz-1/PreciousServices#50]
**Describe the bug**
<img width="1002" alt="image" src="https://github.com/SyedImtiyaz-1/PreciousServices/assets/115429121/d5adfd50-affa-4b03-a240-f3cc73d29da2">
right beside the contact button there's all of the contact info therefore there's no use of the contact button plus they have the same functionality. so either the contact button needs to be removed or the info needs to be removed.
**To Reproduce**
scroll all the way down to the web page thats where you'll find the contact button and all of the contact info right beside each other

**Expected behavior**

**Screenshots**

**Additional context**

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [ ] Have you added your name in [CONTRIBUTING.md](https://github.com/SyedImtiyaz-1/PreciousServices/blob/main/CONTRIBUTING.md)
- [x] I want to work on this issue

**Comment by SyedImtiyaz-1** [comment]
Go for it.
